[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Enables or disables via-ir
via-ir = false
# Enables or disables the optimizer
optimizer = false
# Version to compile with
solc_version = "0.8.28"
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts-upgradable/=lib/openzeppelin-contracts-upgradable/",
    "ustb/=lib/ustb"
]

# Contracts to track with --gas-report
#gas_reports = []

[fuzz]
# Amount of runs per fuzz test
runs = 4098

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
