[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Enables or disables via-ir
via-ir = false
# Enables or disables the optimizer
optimizer = false
# The number of optimizer runs
optimizer_runs = 2_000 # TODO
# Version to compile with
solc_version = "0.8.26"

# Contracts to track with --gas-report
#gas_reports = []

[fuzz]
# Amount of runs per fuzz test
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
